### ISSUE TITLE
使用上的小问题

### ISSUE THREAD

**Issue by lupus721** [qq4108863/hihttps#1]
使用上有一些小问题
1、如果我已经有一个干净的用户访问url列表，怎么重新训练规则集
2、在doc文件夹下看到有web界面的后台，没有找到怎么进啊
3、如何能生成全量日志，就是我希望不止是被拦截的有告警，正常用户访问也给记录下来，方便我复查那些规则没有被识别，以后进行拦截

**Comment by qq4108863** [comment]
1、编写代码提取样本格式，生成对抗规则，人工干预核对。
2、web我们没开放，需要付费定制。
3、详细日志我们的专业版才有，可以给源码或者定制。更多可以加我微信wmkwang

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jonny <notifications@github.com&gt;
发送时间: 2020年2月28日 16:41
收件人: qq4108863/hihttps <hihttps@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[qq4108863/hihttps] 使用上的小问题 (#1)




使用上有一些小问题
 1、如果我已经有一个干净的用户访问url列表，怎么重新训练规则集
 2、在doc文件夹下看到有web界面的后台，没有找到怎么进啊
 3、如何能生成全量日志，就是我希望不止是被拦截的有告警，正常用户访问也给记录下来，方便我复查那些规则没有被识别，以后巡礼兰
